#!/usr/bin/env python3
"""Build script: processes dictionary.txt + custom_words.txt into words.js for Infinibee."""

import json
from pathlib import Path

BASE_DIR = Path(__file__).parent
DICT_PATH = BASE_DIR / "dictionary.txt"
CUSTOM_PATH = BASE_DIR / "custom_words.txt"
OUTPUT_PATH = BASE_DIR / "words.js"

MAX_SCORE = 300
VOWELS = set("aeiou")
MIN_VOWELS = 2


def score_word(word, letter_set):
    if len(word) == 4:
        return 1
    unique = set(word)
    is_pangram = len(unique) == 7 and unique <= letter_set
    return len(word) + (7 if is_pangram else 0)


def main():
    seen = set()
    valid = []

    # Load base dictionary (SCOWL-derived, one word per line)
    for line in DICT_PATH.read_text().splitlines():
        w = line.strip().lower()
        if not w.isalpha() or len(w) < 4 or len(set(w)) > 7:
            continue
        if w not in seen:
            seen.add(w)
            valid.append(w)

    # Merge custom words
    if CUSTOM_PATH.exists():
        for line in CUSTOM_PATH.read_text().splitlines():
            w = line.strip().lower()
            if not w or w.startswith("#"):
                continue
            if not w.isalpha() or len(w) < 4 or len(set(w)) > 7:
                continue
            if w not in seen:
                seen.add(w)
                valid.append(w)

    valid.sort()

    # Index words by their unique letter signatures for fast lookup
    by_sig = {}
    for w in valid:
        sig = frozenset(w)
        if sig not in by_sig:
            by_sig[sig] = []
        by_sig[sig].append(w)

    # Find all 7-letter pangram keys with at least 2 vowels
    raw_keys = set()
    for w in valid:
        if len(set(w)) == 7:
            key = frozenset(w)
            if len(key & VOWELS) >= MIN_VOWELS:
                raw_keys.add(key)

    # For each key, test each possible center letter
    # Keep only (key, center) pairs where:
    #   - max_score <= MAX_SCORE
    #   - at least one pangram exists (guaranteed since key came from a 7-unique-letter word)
    puzzles = []
    skipped_high = 0
    for key in sorted(raw_keys, key=lambda k: "".join(sorted(k))):
        letter_set = set(key)
        # Find all valid words for this letter set (any center)
        all_words = []
        for sig, words in by_sig.items():
            if sig <= key:
                all_words.extend(words)

        for center in sorted(key):
            # Filter words that include the center letter
            puzzle_words = [w for w in all_words if center in w]
            if not puzzle_words:
                continue

            # Check at least one pangram
            has_pangram = any(len(set(w)) == 7 for w in puzzle_words)
            if not has_pangram:
                continue

            # Calculate max score
            total = sum(score_word(w, letter_set) for w in puzzle_words)
            if total > MAX_SCORE:
                skipped_high += 1
                continue

            puzzles.append("".join(sorted(key)) + center)

    print(f"Valid words: {len(valid)}")
    print(f"Raw pangram letter sets: {len(raw_keys)}")
    print(f"Skipped (score > {MAX_SCORE}): {skipped_high}")
    print(f"Valid puzzles (key+center): {len(puzzles)}")

    # Write as a JS module
    with open(OUTPUT_PATH, "w") as f:
        f.write("// Auto-generated by build.py — do not edit\n")
        f.write(f"const WORDS = {json.dumps(valid)};\n")
        f.write(f"const PUZZLES = {json.dumps(puzzles)};\n")

    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"Wrote {OUTPUT_PATH} ({size_kb:.0f} KB)")


if __name__ == "__main__":
    main()
